import Pagination from '@/components/pagination'
import ProductList from '@/components/product-list'
import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import PropTypes from 'prop-types'
import { useEffect, useMemo, useState } from 'react'

export default function Home({products}) {
  console.log('products', products)
  const [page, setPage] = useState(1)
  useEffect(()=> {
    console.log('page', page)
  }, [page])
  const prevPage = () => {
    setPage(prev => prev !== 1 ? prev-1 : 1)
  }
  const nextPage = () => {
    setPage(prev => prev+1)
  }
  const onPageChange = (e) => {
    if (Number(e.target.value)>0) {
      setPage(Number(e.target.value))
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ProductList items={products} perPage={12} page={page}></ProductList>
        <Pagination totalItems={products.length} perPage={12} currentPage={page} onPageChange={onPageChange} nextPage={nextPage} prevPage={prevPage}></Pagination>
      </main>
    </>
  )
}


export async function getServerSideProps(context) {
  const {data :products} = await axios.get('https://jsonplaceholder.typicode.com/posts')
  return {
    props: {
      products: products || [],
    }, 
  }
}


Home.propTypes = {
  products: PropTypes.array
}